server:
  port: ${AUTH_PORT:8081}
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/eastbill_identity}
    username: ${AUTH_DB_USERNAME:postgres}
    password: ${AUTH_DB_PASSWORD:123456}
  sql:
    init:
      mode: always
jwt:
  secret: ${JWT_SECRET:eastbill-local-dev-secret-change-before-deploy}
  expire: ${JWT_EXPIRE:86400}
springdoc:
  packages-to-scan: com.user
