CREATE TABLE IF NOT EXISTS app_user (
  user_id BIGSERIAL PRIMARY KEY,
  account VARCHAR(50) NOT NULL,
  user_name VARCHAR(50),
  password VARCHAR(100) NOT NULL,
  role VARCHAR(10) NOT NULL DEFAULT '2',
  create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_app_user_account UNIQUE (account)
);
