CREATE TABLE IF NOT EXISTS `user` (
  user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  account VARCHAR(50) NOT NULL,
  user_name VARCHAR(50),
  password VARCHAR(100) NOT NULL,
  role VARCHAR(10) NOT NULL DEFAULT '2',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  UNIQUE KEY uk_user_account (account)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
