server:
  port: ${BILL_PORT:8083}
spring:
  application:
    name: bill-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${BILL_DB_URL:jdbc:postgresql://localhost:5432/eastbill_bill}
    username: ${BILL_DB_USERNAME:postgres}
    password: ${BILL_DB_PASSWORD:123456}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
springdoc:
  packages-to-scan: com.bill
