CREATE TABLE IF NOT EXISTS `flight` (
    `flight_id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `flight_no` VARCHAR(20) NOT NULL,
    `company` VARCHAR(50) NOT NULL,
    `aircraft_reg` VARCHAR(20) NOT NULL,
    `aircraft_type` VARCHAR(30) NOT NULL,
    `seat_no` VARCHAR(20) NOT NULL,
    `departure_icao` CHAR(4) NOT NULL,
    `departure_airport` VARCHAR(50) NOT NULL,
    `departure_terminal` VARCHAR(20) NOT NULL,
    `takeoff_time` DATETIME NOT NULL,
    `boarding_method` VARCHAR(20) NOT NULL,
    `arrival_icao` CHAR(4) NOT NULL,
    `arrival_airport` VARCHAR(50) NOT NULL,
    `arrival_terminal` VARCHAR(20) NOT NULL,
    `landing_time` DATETIME NOT NULL,
    `deplaning_method` VARCHAR(20) NOT NULL,
    `stopover_airport` VARCHAR(50) DEFAULT NULL,
    `flight_distance_km` INT NOT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`flight_id`),
    KEY `idx_flight_user` (`user_id`),
    KEY `idx_flight_no` (`flight_no`),
    KEY `idx_flight_takeoff_time` (`takeoff_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `train` (
    `train_id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `train_no` VARCHAR(20) NOT NULL,
    `train_type` VARCHAR(20) NOT NULL,
    `train_model` VARCHAR(30) DEFAULT NULL,
    `start_station` VARCHAR(50) NOT NULL,
    `end_station` VARCHAR(50) NOT NULL,
    `origin_station` VARCHAR(50) NOT NULL,
    `terminal_station` VARCHAR(50) NOT NULL,
    `departure_datetime` DATETIME NOT NULL,
    `arrival_datetime` DATETIME NOT NULL,
    `seat_no` VARCHAR(20) NOT NULL,
    `seat_class` VARCHAR(20) NOT NULL,
    `mileage_km` INT DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`train_id`),
    KEY `idx_train_user` (`user_id`),
    KEY `idx_train_no` (`train_no`),
    KEY `idx_train_departure_time` (`departure_datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `train_station` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `train_id` BIGINT NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `station_name` VARCHAR(50) NOT NULL,
    `station_order` INT NOT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_station_train` (`train_id`),
    KEY `idx_station_user` (`user_id`),
    KEY `idx_station_name` (`station_name`),
    CONSTRAINT `fk_station_train` FOREIGN KEY (`train_id`) REFERENCES `train` (`train_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `foot_spot` (
    `spot_id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 1,
    `adcode` CHAR(6) NOT NULL,
    `spot_name` VARCHAR(100) NOT NULL,
    `spot_type` VARCHAR(20) NOT NULL,
    `visit_type` VARCHAR(20) NOT NULL DEFAULT 'travel',
    `visit_time` DATE DEFAULT NULL,
    `longitude` DECIMAL(10,7) DEFAULT NULL,
    `latitude` DECIMAL(10,7) DEFAULT NULL,
    `travel_note` VARCHAR(1000) DEFAULT NULL,
    `image_url` VARCHAR(500) DEFAULT NULL,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`spot_id`),
    KEY `idx_foot_user_adcode` (`user_id`, `adcode`),
    KEY `idx_foot_visit_time` (`visit_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
